POST http://localhost:3000/api/profile
Content-Type: application/json

{
  "_id": "6564e8c85bcb227a610115e5",
  "firstname": "Sam",
  "lastname": "Altman",
  "age": 30,
  "gender": "male",
  "role": "Designer"
}

###

POST http://localhost:3000/api/profile
Content-Type: application/x-www-form-urlencoded

firstname=urlencoded&lastname=test&age=52
